# Generated by Django 4.1.3 on 2022-12-03 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='favoritegenres',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoritesong',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='songlyrics',
            name='song_title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistitems',
            name='album',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='playlistitems',
            name='artist',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='playlistitems',
            name='song',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='songlyrics',
            name='artist',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='songlyrics',
            name='lyrics',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='songlyrics',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dash_app.song'),
        ),
        migrations.DeleteModel(
            name='FavoriteArtist',
        ),
        migrations.DeleteModel(
            name='FavoriteGenres',
        ),
        migrations.DeleteModel(
            name='FavoriteSong',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='userpreferencerecord',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_app.artist'),
        ),
        migrations.AddField(
            model_name='userpreferencerecord',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_app.genre'),
        ),
        migrations.AddField(
            model_name='userpreferencerecord',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash_app.song'),
        ),
        migrations.AddField(
            model_name='userpreferencerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
